### ISSUE TITLE
[Overview] Chapter 5

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#40]
# TODO

- [x] Add powerpoint
- [x] Fix that we need to specify `collaboration` in `client.study.list` to fix the offline node issue
- [x] encryption is mentioned in basic concepts. I don't think we handle vantage6 encryption anywhere before that, but I think we should mention it somewhere. Maybe we can mention it when creating collaboration in the UI?
- [x] In challenge 1, we should fill in the SERVER_URL. And maybe also the version once we fixed it for the workshop
  - [x] The solution should include the constructed script
  - [x] The solution output should be in text and not an image
- [x] #151
- [x] Still includes TODOs - resolve those
* [x] In Overview. Objective: "Start PET analysis using the python client". As now it sounds more like a theoretical exercise. 
* [x] In Overview. Someone notified me that we should not use credentials in text based formats. I agree so we should not make statements like "To keep your connection details separated and secure, they should be defined in a separate Python module:". Either dont mention that this is secure or figure out a way to do it proper with a keychain solution. The reason why we do it so that the credentials are not visible when making screencaps or in a call.
* [x] In Overview. Make the link from: "See Chapter 3’s concept map"
* [x] In Using the client. I think we should also explain the response structure, especially with the `.list` as it is paginated.
* [x] In Using the client. "the task will begin running in the background" -> the task will be send to the nodes by the server to be executed, this call will not wait for the results.
* [x] In Using the client. The distinction between `result = client.wait_for_results(task_id)` and `result_info = client.result.from_task(task_id=task_id)` is not clear to me.
- [x] Add future changes to chapters
- [x] Clean all responses (make some dummy ones)
- [x] Add a challenge to inspect the log files
- [x] Advanced challenges

**Comment by frankcorneliusmartin** [comment]
@wbaccinelli I think 

> encryption is mentioned in basic concepts. I don't think we handle vantage6 encryption anywhere before that, but I think we should mention it somewhere. Maybe we can mention it when creating collaboration in the UI?

Should be landing in chapter 2.

**Comment by dsmits** [comment]
Bit more feedback: #69

**Comment by wbaccinelli** [comment]
> @wbaccinelli I think
> 
> > encryption is mentioned in basic concepts. I don't think we handle vantage6 encryption anywhere before that, but I think we should mention it somewhere. Maybe we can mention it when creating collaboration in the UI?
> 
> Should be landing in chapter 2.

I agree, I can introduce it in the basics.

**Comment by frankcorneliusmartin** [comment]
Feedback from the try-outs (to be processed):

- I would say, make it interactive, including a jupyter lab thing
- try to actually use jupyterlab for the actual workshop. it's easier for the participants that may already be confused by the material if at least the visuals are identical to what it looks like on their own screen.
- Make sure we are ready to unblock users
- Stress that we should only use Jupyter lab
- See if notes work as live coding session (live coding)
- the fields argument is not listed in the docstring, please do not use undocumented arguments
- Make clear that ppl should log in with researcher user, not admin one
- For teaching, log level info is nice
- Include the help() function earlier in the beginning - I think it should be known before the first exercise instead of just after (if I noted this correctly)
- It would be nice to emphasize when to use the client - it's easier to use the UI, this is mostly useful for automating stuff
