### ISSUE TITLE
[Overview] Chapter 7

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-workshop#44]
This is an overview issue for chapter 7

# TODOs
- [ ] Powerpoint slides
- [x] Still has TODOs in the text
- [x] Still has content depending on workshop infrastructure #30 
- [x] if we have UI + algo store in `vdev`, we need to add some details on where things are running (server on port 5000, UI on port 5001, store on 5002)
- [x] for this to work locally on `vdev`, we also need a policy for the algorithm store to not require reviews
- [x] Maybe to show some sort of image in the "Algorithm Tools" section? So that you know where these operate? (=the interface between the node and algorithm)
![image](https://github.com/user-attachments/assets/409dc876-8177-4df1-a92b-0178c83f9349)
- [x] In create a simple algorithm. "These requirements" -> now it sounds like that there are many requirements whilst you only mention one in the previous sentence.
- [x] The first step in "Create a simple algorithm" you mention to create a new env and install vantage6. I prefer just pointing them to the setup section: `/index.html#python-environment-and-python-packages`
- [x] The solution of the first answer should give a little bit more. Maybe show the generated files here? Or a link to a repo. 
- [x] In implement the algorithm functions. Maybe we could hint them the pandas functions they should use or a link to the panda docs. I think everyone should be familiar but maybe good to provide references so they can also look it up. E.g. https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum
- [x] In Test your algorithm using the mock client. Now only the output has been provided,  i think the scripts themself are also important.
✔️ cool that you already added the workshop project in Harbor to the requirements 
- [x] In Challenge 4: Test your algorithm on a local vantage6 network. I think it is good to provide credentials and server details for the client. 
- [x] I would expect another challenge after challenge 5. Run the algorithm from the UI.
- [x] In next steps, maybe refer to a repository who has such guards?
- [ ] #72 
- [x] Check if `v6 algorithm update --change-answers` works

# Discuss 
- [x] @frankcorneliusmartin @hcadavid we talked about changing the algorithm they have to implement to min/max instead of average, right?
- [x] Add future changes to chapters
