### ISSUE TITLE
[Overview] Chapter 3

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#46]
**Desired solution**

TODO:
- [X] (fixed) @bartvanbL: the UI issue reported here: https://github.com/vantage6/vantage6/issues/1478 is one with a significant impact on the participants' experience.
- [X] Add KM algorithm #38 
- [X] Powerpoint slides
- [X] Screenshots need to be updated. Best after release 4.6
	- This also requires text to be updated slightly
- [X]  Still contains TODOs
- [X]  Overview: How does a vantage6 collaboration work? -> What is a vantage6 collaboration?
- [X]  Overview: How to run a task through vantage6’s UI? -> How to start a federated analysis using the UI?
- [X]  Overview: vantagee6 -> vantage6
- [X]  Vantage6 user interface basics: "**Result**: the output generated by the execution of an **algorithm** as part of a **task**." -> - **Result**: the output generated by the execution on a single node of an **algorithm** as part of a **task**.
- [X]  Challenge 4 (adding alg-store to a collaboration) must be removed. As discussed previously, the workshop infrastructure requires multiple participants to work on a common collaboration, so it is no longer possible for all of them to do this exercise.
- [x] Include #25 
- [x] Include #24
- [x] Include #33 
- [X] Update the section about the algorithm store: it is outdated, e.g. algorithm review process is now available
- [X] We should also discuss whether there should be some screenshots of the algorithm store UI. I'm guessing not too much but a bit of the structure could be nice. Not sure whether it should go in this lesson though, but it should be somewhere. (already discussed, won't be included)

Discuss:
- [X]  Challenge 2 involves analysis of the code of the average algorithm. This is a bit tricky for day 1 where people don't necessarily know Python (already discussed)
- [X]  Where are these concepts in the UI?: In the first challenge "CHALLENGE 1: GET FAMILIAR WITH THE VANTAGE6 UI". Let them set their Last name?
- [X]  Where are these concepts in the UI?: Challenges need to be updated to reflect the results from the infra discussion we had in June.
- [X] This will be addressed in one of the dry-run comments. @bartvanb I believe the comments included in it should help participants to grasp the general idea, even if they don't know Python. However, we could also include the algorithm pseudo-code.
- [X]  In our earliest discussions about the workshop content we decided not to include the concept of 'Study'. However, as discussed https://github.com/vantage6/vantage6-workshop/issues/30 we will use it to set up the node configurations for all the participants. I assume this will require updating the steps where the analysis is performed on a collaboration, so it is done on a study instead. This will require updating the concept map of the introduction and the diagram of the 'collaboration' scenario.
- [X] Add section on future work with sessions/chaining (out of the scope of this episode)

**Comment by dsmits** [comment]
More feedback #68

**Comment by frankcorneliusmartin** [comment]
@hcadavid when adding the Kaplan-Meier, let me know.. I can help :)

**Comment by CunliangGeng** [comment]
@hcadavid The screenshot for UI admin page changed, you may also need it:

- The original file to annotate the figure:  https://github.com/vantage6/vantage6-workshop/blob/47-chapter4-overview-round2/episodes/fig/chapter4/chapter4_raw_figure.drawio
- The figure: https://github.com/vantage6/vantage6-workshop/blob/47-chapter4-overview-round2/episodes/fig/chapter4/ui_admin_page.png

**Comment by hcadavid** [comment]
@frankcorneliusmartin as discussed with @bartvanb, I believe that for this episode is paramount to work with a simple algorithm, as one of the steps involves analyzing it. I think the federated average is perfect given its simplicity and that it is explained in previous episodes. 

As some participants may not be able to understand the code and concepts behind the KM algorithm (in reasonable time), I think it could be included as an optional challenge at the end.
