### ISSUE TITLE
[Overview] Chapter 4

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-workshop#47]
This is an overview for [chapter 4](https://workshop.vantage6.ai/chap4_manage_via_ui.html).

# TODOs
- ~~Create powerpoint~~
- [x]  Screenshots need to be updated. Best after release 4.6 
	- This also requires text to be updated slightly
- [x] Challenge 1 has to be updated - we should decide on workshop infra #30  to see what users can do
- ~~In chapter 3, there is already a challenge 4 to add an algorithm store to a collaboration. So then the page to view a specific collaboration should already be familiar at that point. Not sure what to do about this yet.~~ 
**🦊 Nothing to do with this. Ch3 focuses on a quick try while ch4 focuses on creating a collaboration, the purposes are different even though there are a bit overlapped content**

* [x] In Vantage6 permission system. Add that not every resource has all scopes and or operation. Now it seems like the root user does not have all permissions.
* [x] Vantage6 permission system. Maybe we can add a challenge to understand that they cannot grant permissions to other user (or when they create a new one) that they do not own themselves. Maybe we can do that in "Create a new user" section. 
**🦊 I added one more question in Challenge 2 for this.**
- ~~In Manage vantage6 project using the UI. "vantage6 UI administration page" Image is broken~~
* [x] Manage vantage6 project using the UI. "1. - The `Upload public key` field is optional. You can upload a public key for the organization if you want to use encryption in the collaboration." mention that we do not use it during the workshop.
* [x] Manage vantage6 project using the UI. "If no nodes are registered, you can register them manually by clicking the `Register missing nodes` button." -> "In case one or more organizations did not registered the node when creating or updating the collaboration, you can register them manually by clicking the `Register missing nodes` button."

# Dicuss
* [x] "### CHALLENGE 2: MANAGE VANTAGE6 PROJECT USING THE UI" -> maybe we can make it a bit more challenging by asking them to register a user with specific limitations? Regisiter a user who also can edit the collaboration details. Or maybe something that makes a little bit more sense.
* ~~Maybe we should let them reset an API key? (they should be logged into the dummy environment and not the one they are going to use for actual analysis, we discussed this with Hector, should be included in #30 )~~  
**🦊  It's covered by chapter 6**

* ~~I think we also should explain the Study concept here. Why you would want to create one.~~ 
**🦊 This should be discussed in ch3, which is a TODO in the #46**
* [x] The workshop's shared 'collaborations' would also pose a problem for this chapter that needs to be further discussed. What about creating a 'sandbox' server (no running nodes would be needed), separate from the one used for the other chapters, just for the participants to play with the management features? We should include this in #30. 
**🦊  The infra already includes a dummy server for that.**
* [ ] Add future changes to chapters
